sweettooth/review/urls.py
from django.urls import path, re_path
from django.views.generic.list import ListView

from sweettooth.extensions.models import ExtensionVersion
from sweettooth.review import views

urlpatterns = [
    re_path(
        r"^$",
        ListView.as_view(
            template_name="review/list.html",
            queryset=ExtensionVersion.objects.unreviewed().order_by("pk"),
            context_object_name="version_list",
        ),
        name="review-list",
    ),
    re_path(
        r"^ajax/get-file/(?P<pk>\d+)",
        views.ajax_get_file_view,
        name="review-ajax-files",
    ),
    path(
        "ajax/get-file-list/<int:pk>",
        views.ajax_get_file_list_view,
        name="review-ajax-file-list",
    ),
    path(
        "ajax/get-file-list/<int:pk>/<int:old_version_pk>",
        views.ajax_get_file_list_view,
    ),
    path(
        r"ajax/get-file-diff/<int:pk>",
        views.ajax_get_file_diff_view,
        name="review-ajax-file-diff",
    ),
    path(
        "ajax/get-file-diff/<int:pk>/<int:old_version_pk>",
        views.ajax_get_file_diff_view,
        name="review-ajax-file-diff-against",
    ),
    re_path(r"^submit/(?P<pk>\d+)", views.submit_review_view, name="review-submit"),
    re_path(
        r"^download/(?P<pk>\d+)\.shell-extension.zip$",
        views.download_zipfile,
        name="review-download",
    ),
    re_path(r"^(?P<pk>\d+)", views.review_version_view, name="review-version"),
]

sweettooth/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path, re_path
from django.views import static
from django.views.generic.base import TemplateView
from django.views.i18n import JavaScriptCatalog

admin.autodiscover()

urlpatterns = [
    path("api/", include("sweettooth.api.v1.urls")),
    # 'login' and 'register'
    re_path(r"^accounts/", include("sweettooth.auth.urls")),
    re_path(r"^", include("sweettooth.extensions.urls"), name="index"),
    re_path(r"^review/", include("sweettooth.review.urls")),
    re_path(r"^jsi18n/$", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^comments/", include("sweettooth.ratings.urls")),
    re_path(r"^comments/", include("django_comments.urls")),
    re_path(
        r"^robots\.txt$",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
]

if settings.DEBUG:
    # Use static.serve for development...
    urlpatterns.append(
        re_path(
            r"^extension-data/(?P<path>.*)",
            static.serve,
            dict(document_root=settings.MEDIA_ROOT),
            name="extension-data",
        )
    )
else:
    # and a dummy to reverse on for production.
    urlpatterns.append(
        re_path(
            r"^extension-data/(?P<path>.*)",
            lambda *a, **kw: HttpResponse(),
            name="extension-data",
        )
    )

sweettooth/review/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Group, Permission
from django.db import models
from django.db.models import Q

from sweettooth.extensions.models import STATUSES, ExtensionVersion


def get_all_reviewers():
    perm = Permission.objects.get(codename="can-review-extensions")

    # Dark magic to get all the users with a specific permission
    # Thanks to <schinckel> in #django
    groups = Group.objects.filter(permissions=perm)
    return (
        get_user_model()
        .objects.filter(
            Q(is_superuser=True) | Q(user_permissions=perm) | Q(groups__in=groups)
        )
        .distinct()
    )


class CodeReview(models.Model):
    reviewer = models.ForeignKey(
        settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL
    )
    date = models.DateTimeField(auto_now_add=True)
    comments = models.TextField(blank=True)
    version = models.ForeignKey(
        ExtensionVersion, on_delete=models.CASCADE, related_name="reviews"
    )
    new_status = models.PositiveIntegerField(choices=STATUSES.items(), null=True)
    auto = models.BooleanField(default=False)

    class Meta:
        permissions = (
            ("can-review-extensions", "Can review extensions"),
            ("trusted", "Trusted author"),
        )

sweettooth/review/views.py
import base64
import itertools
import os.path
from collections import Counter
from collections.abc import Sequence
from contextlib import ExitStack
from typing import IO
from zipfile import ZipFile

import pygments
import pygments.formatters
import pygments.lexers
import pygments.util
from django.core.mail import EmailMessage, get_connection
from django.http import Http404, HttpResponseBadRequest, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.views.decorators.http import require_POST

from sweettooth.decorators import ajax_view, model_view
from sweettooth.extensions import models
from sweettooth.review.diffutils import get_chunks
from sweettooth.review.models import CodeReview, get_all_reviewers

IMAGE_TYPES = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".gif": "image/gif",
    ".bmp": "image/bmp",
    ".svg": "image/svg+xml",
}

# Keep this in sync with the BINARY_TYPES list at the top of review.js
BINARY_TYPES = set([".mo", ".compiled"])


# Stolen from ReviewBoard
# See the top of diffutils.py for details
class NoWrapperHtmlFormatter(pygments.formatters.HtmlFormatter):
    """An HTML Formatter for Pygments that don't wrap items in a div."""

    def _wrap_div(self, inner):
        # Method called by the formatter to wrap the contents of inner.
        # Inner is a list of tuples containing formatted code. If the first item
        # in the tuple is zero, then it's a wrapper, so we should ignore it.
        for tup in inner:
            if tup[0]:
                yield tup


code_formatter = NoWrapperHtmlFormatter(style="borland", cssclass="code")


def can_review_extension(user, extension):
    if user == extension.creator:
        return True

    if user.has_perm("review.can-review-extensions"):
        return True

    return False


def can_approve_extension(user, extension):
    return user.has_perm("review.can-review-extensions")


def highlight_file(filename, raw, formatter):
    try:
        lexer = pygments.lexers.guess_lexer_for_filename(
            filename, raw, encoding="chardet"
        )
    except pygments.util.ClassNotFound:
        # released pygments doesn't yet have .json
        # so hack around it here.
        if filename.endswith(".json"):
            lexer = pygments.lexers.get_lexer_by_name("js")
        else:
            lexer = pygments.lexers.get_lexer_by_name("text")

    try:
        return pygments.highlight(raw, lexer, formatter)
    except TypeError:
        # Fallback to UTF-8 for old broken pygments version
        lexer.encoding = "utf-8"
        return pygments.highlight(raw, lexer, formatter)


def html_for_file(filename: str, file: IO[bytes]):
    _, extension = os.path.splitext(filename)

    if extension in BINARY_TYPES:
        return None
    elif extension in IMAGE_TYPES:
        mime = IMAGE_TYPES[extension]
        return dict(
            raw=True,
            html='<img src="data:%s;base64,%s">'
            % (
                mime,
                base64.standard_b64encode(file.read()).decode("ascii"),
            ),
        )
    else:
        return dict(
            raw=False,
            lines=highlight_file(filename, file.read(), code_formatter).splitlines(),
        )


def get_old_version(version):
    extension = version.extension

    # Try to get the latest version that's less than the current version
    # that actually has a source field. Sometimes the upload validation
    # fails, so work around it here.
    try:
        old_version = (
            extension.versions.filter(
                version__lt=version.version,
                status__in=(models.STATUS_ACTIVE, models.STATUS_INACTIVE),
            )
            .exclude(source="")
            .latest()
        )
    except models.ExtensionVersion.DoesNotExist:
        try:
            old_version = (
                extension.versions.filter(version__lt=version.version)
                .exclude(source="")
                .earliest()
            )
        except models.ExtensionVersion.DoesNotExist:
            # There's nothing before us that has a source, or this is the
            # first version.
            return None

    return old_version


def get_zipfiles(*args: tuple[models.ExtensionVersion]):
    for version in args:
        if version is None:
            yield None
        else:
            yield version.get_zipfile("r")


def grab_lines(zipfile: ZipFile, filename: str):
    try:
        with zipfile.open(filename, "r") as f:
            return f.read().decode("utf-8").splitlines()
    except (KeyError, UnicodeDecodeError):
        return None


def get_file_list(zipfile):
    return set(n for n in zipfile.namelist() if not n.endswith("/"))


def get_file_changeset(old_zipfile: ZipFile, new_zipfile: ZipFile):
    with new_zipfile:
        new_filelist = get_file_list(new_zipfile)
        if old_zipfile is None:
            return dict(
                unchanged=[], changed=[], added=sorted(new_filelist), deleted=[]
            )

        with old_zipfile:
            old_filelist = get_file_list(old_zipfile)

            both = new_filelist & old_filelist
            added = new_filelist - old_filelist
            deleted = old_filelist - new_filelist

            unchanged, changed = set(), set()

            for filename in both:
                with (
                    old_zipfile.open(filename, "r") as old,
                    new_zipfile.open(filename, "r") as new,
                ):
                    while True:
                        oldcontent, newcontent = old.read(1024), new.read(1024)
                        if not oldcontent or not newcontent:
                            if oldcontent or newcontent:
                                changed.add(filename)
                            else:
                                unchanged.add(filename)

                            break

                        if oldcontent != newcontent:
                            changed.add(filename)
                            break

            return dict(
                unchanged=sorted(unchanged),
                changed=sorted(changed),
                added=sorted(added),
                deleted=sorted(deleted),
            )


@ajax_view
@model_view(models.ExtensionVersion)
def ajax_get_file_list_view(request, version, old_version_pk: int | None = None):
    if old_version_pk:
        old_version = get_object_or_404(models.ExtensionVersion, pk=old_version_pk)
        if old_version.extension != version.extension:
            return HttpResponseBadRequest()
    else:
        old_version = get_old_version(version)

    return get_file_changeset(*get_zipfiles(old_version, version))


@ajax_view
@model_view(models.ExtensionVersion)
def ajax_get_file_diff_view(
    request, version: models.ExtensionVersion, old_version_pk: int | None = None
):
    filename = request.GET["filename"]

    _, file_extension = os.path.splitext(filename)
    if file_extension in IMAGE_TYPES:
        return None

    if file_extension in BINARY_TYPES:
        return None

    if old_version_pk:
        old_version = get_object_or_404(models.ExtensionVersion, pk=old_version_pk)
        if old_version.extension != version.extension:
            return None
    else:
        old_version = get_old_version(version)

    old_zipfile, new_zipfile = get_zipfiles(old_version, version)
    oldlines, newlines = (
        grab_lines(old_zipfile, filename),
        grab_lines(new_zipfile, filename),
    )

    chunks = list(get_chunks(oldlines, newlines))
    return dict(chunks=chunks, oldlines=oldlines, newlines=newlines)


def get_changelog(old_version, new_version, filename="CHANGELOG"):
    old_zipfile, new_zipfile = get_zipfiles(old_version, new_version)
    oldlines, newlines = (
        grab_lines(old_zipfile, filename),
        grab_lines(new_zipfile, filename),
    )
    chunks = get_chunks(oldlines, newlines)

    contents = []
    for chunk in chunks:
        if chunk["operation"] != "insert":
            continue

        content = "\n".join(newlines[line["newindex"]] for line in chunk["lines"])
        contents.append(content)

    return "\n\n".join(contents)


@ajax_view
@model_view(models.ExtensionVersion)
def ajax_get_file_view(request, obj):
    filename = request.GET["filename"]

    with obj.get_zipfile("r") as zipfile:
        try:
            with zipfile.open(filename, "r") as f:
                return html_for_file(filename, f)
        except KeyError:
            raise Http404()


def download_zipfile(request, pk):
    version = get_object_or_404(models.ExtensionVersion, pk=pk)
    return redirect(version.source.url)


@require_POST
@model_view(models.ExtensionVersion)
def submit_review_view(request, obj):
    extension, version = obj.extension, obj

    can_approve = can_approve_extension(request.user, extension)
    can_review = can_review_extension(request.user, extension)

    if not can_review:
        return HttpResponseForbidden()

    status_string = request.POST.get("status")
    newstatus = dict(
        approve=models.STATUS_ACTIVE,
        wait=models.STATUS_WAITING,
        reject=models.STATUS_REJECTED,
    ).get(status_string, None)

    if newstatus and not can_approve:
        return HttpResponseForbidden()

    # If a normal user didn't change the status and it was in WAITING,
    # change it back to UNREVIEWED
    if not can_approve and version.status == models.STATUS_WAITING:
        newstatus = models.STATUS_UNREVIEWED

    review = CodeReview(
        version=version, reviewer=request.user, comments=request.POST.get("comments")
    )

    if newstatus:
        review.new_status = newstatus
        version.status = newstatus
        version.save()

    review.save()

    models.reviewed.send(
        sender=request, request=request, version=version, review=review
    )

sweettooth/review/templates/review/list.html
{% extends "base.html" %}
{% load extension_icon %}

{% block title %}Unreviewed Extensions - {{ block.super }}{% endblock %}

{% block body %}
<h2>Unreviewed Extensions</h2>
<ul class="extensions">
{% for version in version_list %}
{% with version.extension as extension %}
<li class="extension">
  <h3 class="extension-name"><a href="{% url 'review-version' pk=version.pk %}"><img src="{% extension_icon extension.icon %}" class="icon">{{ extension.name }}</a></h3>
  <span class="version">({{ version.display_version }})</span>
  <span class="author">by <a href="{% url 'auth-profile' user=extension.creator %}">{{ extension.creator }}</a></span>
  <p class="description">{{ extension.first_line_of_description }}</p>
</li>
{% endwith %}
{% endfor %}
</ul>
{% endblock %}

sweettooth/review/templates/review/review.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}
{% load extension_icon %}

{% block title %}Review "{{ extension.name }}" version {{ version.display_full_version }} - {{ block.super }}{% endblock %}

{% block body %}
<h2>Review of "{{ extension.name }}" version {{ version.display_full_version }}</h2>
<h2 class="expandy_header expanded col-xs-12 col-sm-12 col-md-12 col-lg-12">Details Page Preview</h2>
<div id="preview">
  <div class="extension single-page">
    <div class="extension-header col-xs-12 col-sm-12 col-md-12 col-lg-12">
        {% spaceless %}
            <h3 class="extension-name">
                <a href="{{ extension.get_absolute_url }}">
                    <img src="{% extension_icon extension.icon %}" class="icon">{{ extension.name }}
                </a>
            </h3>

            <span class="author"> by <a
                    href="{% url 'auth-profile' user=extension.creator %}">{{ extension.creator }}</a></span>
        {% endspaceless %}
    </div>

    <div class="extension-details">
        {% if extension.screenshot %}
            <div class="screenshot col-xs-12 col-sm-5 col-md-4 col-lg-3">
                <a href="{{ extension.screenshot.url }}" class="screenshot"><img
                        src="{{ extension.screenshot.url }}"></a>
            </div>

            <div class="col-sm-1 col-md-1 col-lg-1">
            </div>
        {% endif %}

        <div class="col-xs-12 col-sm-6 col-md-7 col-lg-8">
            <p class="description">{{ extension.description }}</p>

            <dl>
                {% if extension.url %}
                    <dt>Extension Homepage</dt>
                    <dd><a href="{{ extension.url }}" id="extension_url">{{ extension.url }}</a></dd>
                {% endif %}
            </dl>
        </div>
    </div>

    <hr>

    No comments.
    <div class="clear"></div>
  </div>
</div>

{% if compare_version %}
<h2 class="expandy_header expanded col-xs-12 col-sm-12 col-md-12 col-lg-12">
    Diff Against
    <select id='diff_version_select'>
    {% for ver in all_versions %}
    {% if ver.version < version.version %}
        <option{% if ver.version == compare_version.version %} selected='selected'{% endif %} value='{{ ver.pk }}'>version {{ ver.display_full_version }} ({{ ver.get_status_display }})</option>
    {% endif %}
    {% endfor %}
    </select>
</h2>
<div id="diff" data-pk="{{ version.pk }}" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
</div>
{% else %}
  <h2 class="expandy_header expanded col-xs-12 col-sm-12 col-md-12 col-lg-12">FAQ</h2>
  <ul>
    <li>
      {% trans "You can upload the next version by the <a href='https://extensions.gnome.org/upload/'>same form</a> you've posted this version." %}
    </li>
    <li>
      {% trans "You can change the extension icon by clicking on the icon in your extension page." %}
    </li>
    <li>
      {% trans "In case you want to inactivate an approved version, click on inactivate link in your extension page." %}
    </li>
    <li>
      {% trans "You can find developer guides in <a href='https://gjs.guide/extensions/'>gjs.guide</a>." %}
    </li>
    <li>
      {% trans "If you need any help with your extension, you can ask us on <a href='https://matrix.to/#/#extensions:gnome.org'>GNOME Matrix Channel</a>." %}
    </li>
  </ul>
{% endif %}

<h2 class="expandy_header{% if not compare_version %} expanded{% endif %} col-xs-12 col-sm-12 col-md-12 col-lg-12">Files</h2>

<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <div id="files" data-pk="{{ version.pk }}">
  </div>
  <p>Note: Binary files aren't shown on the web site. To see all
    files, please <a href="{% url 'review-download' pk=version.pk %}">download
      the extension zipfile</a>.</p>
</div>

<h2 class="expandy_header expanded col-xs-12 col-sm-12 col-md-12 col-lg-12">All Versions</h2>
<div id="all_versions">
  <table>
    <thead>
      <th>Version</th>
      <th>Status</th>
    </thead>
    <tbody>
      {% comment %}
      This is somewhat confusing. 'ver' is the loop variable across
      all extension versions. 'version' is the current version.
      {% endcomment %}
      {% for ver in all_versions %}
      <tr>
        <td> {{ ver.display_full_version }} </td>
        <td>
          {% if ver.version == version.version %}
          <span class="current_version extension-status {{ ver.get_status_class }}">{{ ver.get_status_display }}</span>
          {% else %}
          <a class="extension-status {{ ver.get_status_class }}" href="{% url 'review-version' pk=ver.pk %}">{{ ver.get_status_display }}</a>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% if previous_reviews %}
<h2 class="expandy_header expanded col-xs-12 col-sm-12 col-md-12 col-lg-12">Previous Reviews on this Version</h2>
<div id="previous_reviews" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  {% for review in previous_reviews %}
  <div class="review">
    {% if review.reviewer %}
    <a class="review-author" href="{% url 'auth-profile' user=review.reviewer.username %}">{{ review.reviewer.get_full_name }}</a>
    {% else %}
    Ghost
    {% endif %}
    {% if review.new_status %}
    <span class="extension-status {{ review.get_new_status_display|lower }}">
      {% if review.auto %}auto-{% endif%}
      {{ review.get_new_status_display|lower }}
    </span>
    {% else %}
    posted a review
    {% endif %}
    <time title="{{ review.date|date:"c" }}Z">{{ review.date|date:"F j, Y" }}</time>
    <blockquote>{{ review.comments }}</blockquote>
  </div>
  {% empty %}
  <p>No reviews.</p>
  {% endfor %}
</div>
{% endif %}

{% if can_review %}
<h2 class="expanded col-xs-12 col-sm-12 col-md-12 col-lg-12">Review</h2>

<div id="review" class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  <form id="review_form" action="{% url 'review-submit' pk=version.pk %}" method="POST">
    {% csrf_token %}
    <textarea id="comments" name="comments"></textarea>
    <select name="status">
      <option value="none" selected>No change</option>
{% if can_approve %}
      <option value="approve" class="approve">Approve</option>
      <option value="reject" class="reject">Reject</option>
      <option value="wait" class="waiting">Needs reply from author</option>
{% endif %}
    </select>
    <input type="submit" value="Submit">
  </form>
</div>
{% endif %}

{% endblock %}

{% block head %}
  {{ block.super }}
  <link rel="stylesheet" href="{% static 'css/review.css' %}" />
  <script>
      jQuery(function ($) {
          require(['review-main'], function(){});
      });
  </script>
{% endblock %}